# Generated by Django 2.0.5 on 2018-05-09 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('ON', 'ON')], default='', max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=16)),
                ('employed_from', models.DateField(default=datetime.datetime.now)),
                ('employed_until', models.DateField(blank=True, null=True)),
                ('sin', models.CharField(blank=True, max_length=12, null=True)),
                ('position', models.CharField(choices=[('Estimator', 'Estimator'), ('IT', 'IT'), ('Labour', 'Labour'), ('Manager', 'Manager'), ('Office_Staff', 'Office_Staff'), ('Shingler', 'Shingler')], default='', max_length=25)),
                ('wage', models.CharField(max_length=12)),
                ('driver_lic', models.CharField(blank=True, max_length=12, null=True)),
                ('wsib', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('Citizen', 'Citizen'), ('Permanent_Resident', 'Permanent_Resident'), ('Refugee', 'Refugee'), ('Working_Visa', 'Working_Visa'), ('NONE', 'NONE')], default='', max_length=18)),
                ('clothes_size', models.CharField(choices=[('2XL', '2XL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], default='', max_length=3)),
                ('whmis', models.BooleanField(default=False)),
                ('work_heights', models.BooleanField(default=False)),
                ('worker_health_safety', models.BooleanField(default=False)),
                ('propane_in_construction', models.BooleanField(default=False)),
                ('note', models.TextField()),
            ],
        ),
    ]
