# Generated by Django 2.0.5 on 2018-05-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='city',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
