# Generated by Django 2.0.5 on 2018-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_employees_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='propane_in_construction',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='employees',
            name='whmis',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='employees',
            name='work_heights',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='employees',
            name='worker_health_safety',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
    ]
