# Generated by Django 2.0.5 on 2018-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0003_auto_20180510_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(default='Toronto', max_length=90),
        ),
    ]
